name: "01_Foundation"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment used to deploy urbanos.
        options:
          - dev
          - uat
          - prd
        required: true
      deploy:
          type: choice
          description: Deploy?
          options:
            - plan
            - apply
          required: true
jobs:
  Plan:
    uses: UrbanOS-Public/sky_blue/.github/workflows/az_tf_plan.yml@main
    with:
      path: 01_Foundations                               ## Path to terraform root module (Required)
      tf_version: latest                                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      tf_key: "foundation-${{ github.event.inputs.environment }}"                            ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: ../tfvars/config-${{ github.event.inputs.environment }}.tfvars             ## Terraform TFVARS (Required)
      #enable_TFSEC: true                                ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
      gh_environment: ${{ github.event.inputs.environment }}

  Deploy:
      if: ${{ github.event.inputs.deploy == 'apply' }}
      needs: Plan
      uses: UrbanOS-Public/sky_blue/.github/workflows/az_tf_apply.yml@main
      with:
        path: 01_Foundations                               ## Path to terraform root module (Required)
        tf_version: latest                                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
        tf_key: "foundation-${{ github.event.inputs.environment }}"                           ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
        #enable_TFSEC: true                                ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
        gh_environment: ${{ github.event.inputs.environment }}                       ## GH Environment. Default=null - (Optional)
